# main.yaml - course playbook
- hosts: os_preparation
  user: ubuntu
  become: yes
  become_user: root
  gather_facts: true

  roles:
  #- { role: luks-encryption, tags: luks }
  #- { role: cpu-performance-optimisation, tags: cpu }
  #- { role: network-interface-rename, tags: network }

  tasks:
  - name: Set hyperthreading status 
    set_fact:
      hyperthreading: >-
        {% if  ansible_processor_threads_per_core | int > 1 %}
          Enabled {% else %}
          Disabled {% endif %}

  - name: Display CPU information
    debug:
      msg:
        - "===== CPU Information ====="
        - "Vendor: {{ ansible_processor[1] }}"
        - "CPU Model: {{ ansible_processor[2] }}"
        - "CPU(s): {{ ansible_processor_nproc }}"
        - "Socket(s): {{ ansible_processor_count }}"
        - "Core(s) per socket: {{ ansible_processor_cores }}"
        - "Thread(s) per core: {{ ansible_processor_threads_per_core }}"
        - "Multithreading: {{ hyperthreading }}"
        - "==========================="