---
- name: Install parted
  ansible.builtin.apt:
    name:
      - parted
      - util-linux
    state: present

- name: Check if disk is encrypted with LUKS using blkid
  ansible.builtin.command: blkid -o value -s TYPE {{ target_device }}
  register: blkid_check
  changed_when: false
  failed_when: false

- name: Set variable if disk is already encrypted with LUKS
  ansible.builtin.set_fact:
    disk_already_encrypted: "Disk {{ target_device }} is already encrypted with LUKS. Skipping remaining disk-specific tasks."
  when: "'crypto_LUKS' in blkid_check.stdout"

- name: Check if disk already has GPT partition tables
  ansible.builtin.command: parted -s {{ target_device }} print
  register: parted_check
  changed_when: false
  failed_when: parted_check.rc != 0
  when: disk_already_encrypted is not defined

- name: Set variable if disk already has gpt partition
  ansible.builtin.set_fact:
    disk_with_gpt: Disk {{ target_device }} already has GPT partition, thus it is likely to be in use already. Please check!
  when: "'gpt' in parted_check.stdout"

- name: Create GPT partition table on disks
  ansible.builtin.command: parted -s {{ target_device }} mklabel gpt
  changed_when: false
  when: disk_already_encrypted is not defined and "'gpt' not in parted_check.stdout"

- name: Log warning if tasks skipped
  ansible.builtin.debug:
    msg: >-
      WARNING:
      {% if disk_with_gpt is defined %}
        {{ disk_with_gpt }};
      {% endif %}
      {% if disk_already_encrypted is defined %}
        {{ disk_already_encrypted }};
      {% endif %}
      Disk might contain data! Skipping remaining tasks for {{ target_device }}
  when: disk_with_gpt is defined or disk_already_encrypted is defined

# common encryption tasks
- name: Include common encryption tasks
  ansible.builtin.include_tasks: common.yaml
  vars:
    device_type: "disk"
  when: disk_with_gpt is not defined and disk_already_encrypted is not defined or not ansible_check_mode
