---
- name: Set fact for devices to encrypt
  ansible.builtin.set_fact:
    encrypt_disk: "{{ secondary_disk is defined and secondary_disk != '' }}"
    encrypt_partition: "{{ partition_on_primary is defined and partition_on_primary != '' }}"

- name: Install cryptsetup package
  ansible.builtin.apt:
    name:
      - cryptsetup
      - coreutils
    state: present

- name: Import assert.yaml
  ansible.builtin.import_tasks:
    file: assert.yaml
  vars:
    target_device: "{{ secondary_disk }}"
    target_name: "{{ luks_encryption__disk_mount }}"
  when: encrypt_disk 

- name: Import assert.yaml
  ansible.builtin.import_tasks:
    file: assert.yaml
  vars:
    target_device: "{{ partition_on_primary }}"
    target_name: "{{ luks_encryption__partition_mount }}"
  when: encrypt_partition
  
# encrypt disk if configured
- name: Encrypt disks
  ansible.builtin.include_tasks: disk_specific.yaml
  vars:
    target_device: "{{ secondary_disk }}"
    target_name: "{{ luks_encryption__disk_mount }}"
  when: encrypt_disk and skip_tasks is not defined

# encrypt partition if configured
- name: Encrypt partition
  ansible.builtin.include_tasks: partition_specific.yaml
  vars:
    target_device: "{{ partition_on_primary }}"
    target_name: "{{ luks_encryption__partition_mount }}"
    device_type: "partition"
  when: encrypt_partition and skip_tasks is not defined
