---
# - name: Import assert.yaml
#   ansible.builtin.import_tasks:
#     file: assert.yaml

# common encryption tasks
- name: Include common encryption tasks
  ansible.builtin.include_tasks: common.yaml
  vars:
    device_type: "partition"
