#roles/luks-encryption/tasks/assert.yaml
---
- name: Ensure required variables are defined
  assert:
    that:
      - local_secret_dir is defined 
      - remote_secret_dir is defined 
      - keyfiles_dir is defined
      - headers_dir is defined 
      - keyfile_source_dev is defined 
      - keyfile_size is defined 
      - keyfile_cipher_default is defined 
      - keyfile_cipher_light is defined
    msg: "Missing required variables. Please define local_secret_dir, remote_secret_dir, keyfile_source_dev, keyfile_size, keyfile_cipher_default and keyfile_cipher_light."

- name: Check if devices exist 
  stat:
    path: "{{ target_device }}"
  register: device_stats
  failed_when: not device_stats.stat.exists
    
- name: Gather mount facts
  setup:
    gather_subset:
      - mounts

- name: Set device safe name
  set_fact:
    device_safe_name: "{{ target_device | regex_replace('/', '-') }}"

- name: Set device mapper name
  set_fact:
    device_mapper_name: "/dev/mapper/encrypted{{ device_safe_name }}"

- name: Fail if devices are mounted
  fail:
    msg: "Device {{ device_mapper_name }} is currently mounted. Danger of overwriting data!"
  when:  target_name in ansible_mounts | map(attribute='mount') | list

- name: Fail if device mapper for this device is mounted
  fail:
    msg: "Device mapper for {{ target_device }} is currently mounted. Danger of overwriting data!"
  when: device_mapper_name in ansible_mounts | map(attribute='device') | list

- name: Fail if mount point is already in use
  fail:
    msg: "Mount point {{ target_name }} is already in use. Danger of overwriting data!"
  when: target_name in ansible_mounts | map(attribute='mount') | list

- name: Check if mapper name is already configured in crypttab
  lineinfile:
    path: /etc/crypttab
    regexp: "encrypted{{ device_safe_name }}"
    state: absent
  check_mode: yes
  register: mapper_name_check
  changed_when: false

- name: Fail if mapper name is already configured in crypttab
  fail:
    msg: "Mapper name 'encrypted{{ device_safe_name }}' is already configured in /etc/crypttab. Danger of overwriting data!"
  when: mapper_name_check.found != 0