#roles/luks-encryption/tasks/main.yaml
---
- name: Set fact for devices to encrypt
  set_fact:
    encrypt_disk: "{{ secondary_disk is defined and secondary_disk != '' }}"
    encrypt_partition: "{{ partition_on_primary is defined and partition_on_primary != '' }}"

# install package: cryptsetup
- name: Install cryptsetup package
  apt:
    name: 
      - cryptsetup
      - coreutils
    state: present

# Encrypt disk if configured
- name: Encrypt disks
  include_tasks: disk_specific.yaml
  vars:
    target_device: "{{ secondary_disk }}"
    target_name: "{{ disk_mount }}"
  when: encrypt_disk

# Encrypt partition if configured
- name: Encrypt partition
  include_tasks: common.yaml
  vars:
    target_device: "{{ partition_on_primary }}"
    target_name: "{{ partition_mount }}"
    device_type: "partition"
  when: encrypt_partition