# roles/network-interface-rename/tasks/main.yaml
---

- name: Check if net0 interface exists
  set_fact:
    net0_exists: "{{ new_interface_name in ansible_facts.interfaces }}"

- name: "{{ new_interface_name }} check result"
  debug:
    msg: "Interface {{ new_interface_name }} already exists. Skipping rename process."
  when: net0_exists

- block:
    #1. identify active interface
    - name: Display current active interface facts
      debug:
        msg: "Interface is {{ ansible_default_ipv4.interface }}, Mac is {{ ansible_default_ipv4.macaddress }}"

    #2. get the MAC address and save it as variable
    - name: Check if MAC address was found
      fail:
        msg: "No MAC address found for interface {{ ansible_default_ipv4.interface }}"
      when: ansible_default_ipv4.macaddress is not defined or ansible_default_ipv4.macaddress | length == 0

    #3. find,backup,remove current configs
    - name: Find existing netplan configurations
      find:
        paths: /etc/netplan
        patterns: "*.yaml"
      register: cloud_netplan_files

    - name: Backup current netplan configs
      copy:
        src: "{{ item.path }}"
        dest: "{{ item.path }}.bak"
        remote_src: true
      loop: "{{ cloud_netplan_files.files }}"

    - name: Remove current netplan configs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ cloud_netplan_files.files }}"

    #4. template new configuration
    - name: Create netplan config with renamed interface
      template:
        src: 99-net0-cfg.yaml.j2
        dest: /etc/netplan/99-{{ new_interface_name }}-cfg.yaml
        owner: root
        group: root
        mode: '0600'

    #5. netplan apply
    - name: Apply netplan config
      ansible.builtin.command: netplan apply
      register: netplan_result
      failed_when: netplan_result.rc != 0

    #- name: Wait for a bit
    #  ansible.builtin.pause:
    #    seconds: 2

    #7. display information
    - name: Gather updated facts
      setup:
        gather_subset:
          - network

  when: not net0_exists

- name: Display information about renamed interface
  debug:
    var: ansible_facts.default_ipv4
