#cpu-performance-optimisation/handlers/main.yaml
---
- name: start tuned
  systemd_service:
    name: tuned
    state: restarted
    enabled: yes
    daemon_reload: true

- name: start disable_cstates
  systemd_service:
    name: disable-cstates
    state: restarted
    enabled: yes
    daemon_reload: true